### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by milezzz** [BitMEX/easy-data-scripts#6]
Damn need to do my taxes and cannot seem to get this working. With Python 3.6.5 running on OS X Sierra I get this error...

```
#python3 fetchExecutionTradeHistory.py > bitmex_records.csv

Traceback (most recent call last):
  File "fetchExecutionTradeHistory.py", line 5, in <module>
    from lib import bitmex
  File "/Users/xxxxxxx/Scripts/easy-data-scripts/lib/bitmex.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

I of course inserted my API info in settings.py. Anyone have a clue?

**Comment by milezzz** [comment]
never mind solved with `pip3 install requests`
